global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'host.docker.internal:9090'
  - job_name: spring-actuator
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'host.docker.internal:6868'

  - job_name: mysql
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prom_mysql_exporter:9104'

